/**
 * @description       : 
 * @author            : sakshi.chauhan@simplus.com
 * @group             : 
 * @last modified on  : 11-11-2020
 * @last modified by  : sakshi.chauhan@simplus.com
 * Modifications Log 
 * Ver   Date         Author                       Modification
 * 1.0   11-11-2020   sakshi.chauhan@simplus.com   Initial Version
**/
public class ChartPOCUtility {
    public static final String ytdUniqueReportName = 'YTD Unique (Logged In User)';
    public static final String ytdActualReportName = 'YTD Actual (Logged In User)';
    public static final String ytdTripsReportName = 'YTD Trips (Logged In User)';

    public static final String  ytdTripsTrendReportName = '% YTD TripsTrend (Logged In User)';
    public static final String  ytdUniqueTrendReportName = '% YTD Unique Trend (Logged In User)';
    public static final String  ytdActualTrendReportName = '% YTD Actual Trend (Logged In User)';



    public static final String mtdUniqueReportName = 'MTD Unique (Logged In User)';
    public static final String mtdActualReportName = 'MTD Actual (Logged In User)';
    public static final String mtdTripsReportName = 'MTD Trips (Logged In User)';

    public static final String mtdUniqueTrendReportName = '% MTD Unique Trend (Logged In User)';
    public static final String mtdActualTrendReportName = '% MTD Actual Trend (Logged In User)';
    public static final String mtdTripsTrendReportName = '% MTD Trips Trend (Logged In User)';

    public static final String mtdTheoReportName = 'MTD Theo (Logged In User)';
    public static final String ytdTheoReportName = 'YTD Theo (Logged In User)';

    public static final String reportsFolderName = 'Salesforce Administrative Reports';

    public static final Integer trendRangeNumber = 10;

    
}