public class Exl_PlatformEvent_Inbound_JSONBody {
    @AuraEnabled public String stopCode ; //INBOUND – Synkros Stopcode
    @AuraEnabled public String action ; //INBOUND – Synkros Stopcode
    @AuraEnabled public String poAction ; //INBOUND – PingOne Identity/Access
    @AuraEnabled public String poStatus ; //INBOUND – PingOne Identity/Access
    @AuraEnabled public String appContext; //INBOUND – PingOne Identity/Access
}