public class SalesCompDataProvider {
    
    public class SalesCompJSON{
        
        public string userId;
        public string source;
        public string host;
        public string contextId;
        public string patronId;
        public string reasonCode;
        public string reasonDescription;
        public string staffUser;
        public string approverNotes;
        public string originalTransactionId;
        public string pointValue;
        public string pointTypeIndicator;
        public string pointValueType;
        public string propertyId;
        public string approverUserId;
        public string comments;
    }
}